// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ImagePreviewController from "./image_preview_controller.js";
application.register("image-preview", ImagePreviewController);

import LeafletController from "./leaflet_controller.js";
application.register("leaflet", LeafletController);

import OpeningTimesController from "./opening_times_controller.js";
application.register("opening-times", OpeningTimesController);

import Select2Controller from "./select2_controller.js";
application.register("select2", Select2Controller);

import UserPartnersController from "./user_partners_controller.js";
application.register("user-partners", UserPartnersController);

import PartnerTagsController from "./partner_tags_controller.js";
application.register("partner-tags", PartnerTagsController);

import PartnerAddressController from "./partner_address_controller.js";
application.register("partner-address", PartnerAddressController);
