// LEGACY FILE: This file was used for the esbuild bundle (admin.js)
// The admin interface now uses importmap-rails which auto-loads controllers
// via eagerLoadControllersFrom() - see app/javascript/admin.js
//
// This file is kept for reference but is no longer imported.
// Delete this file once you've verified importmap is working correctly.

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ImagePreviewController from "./image_preview_controller.js";
application.register("image-preview", ImagePreviewController);

import LeafletController from "./leaflet_controller.js";
application.register("leaflet", LeafletController);

import OpeningTimesController from "./opening_times_controller.js";
application.register("opening-times", OpeningTimesController);

import PartnerAddressController from "./partner_address_controller.js";
application.register("partner-address", PartnerAddressController);

import PartnerFilterComponentController from "./partner_filter_component_controller.js";
application.register(
	"partner-filter-component",
	PartnerFilterComponentController
);

import PartnerFormValidationController from "./partner_form_validation_controller.js";
application.register(
	"partner-form-validation",
	PartnerFormValidationController
);

import PartnerTagsController from "./partner_tags_controller.js";
application.register("partner-tags", PartnerTagsController);

import TomSelectController from "./tom_select_controller.js";
application.register("tom-select", TomSelectController);

import AdminTableController from "./admin_table_controller.js";
application.register("admin-table", AdminTableController);

import MultiStepFormController from "./multi_step_form_controller.js";
application.register("multi-step-form", MultiStepFormController);

import UserPartnersController from "./user_partners_controller.js";
application.register("user-partners", UserPartnersController);

import NestedFormController from "./nested_form_controller.js";
application.register("nested-form", NestedFormController);

import DropdownController from "./dropdown_controller.js";
application.register("dropdown", DropdownController);

import CascadingNeighbourhoodController from "./cascading_neighbourhood_controller.js";
application.register(
	"cascading-neighbourhood",
	CascadingNeighbourhoodController
);

import PartnerTabsController from "./partner_tabs_controller.js";
application.register("partner-tabs", PartnerTabsController);

import AutoExpandController from "./auto_expand_controller.js";
application.register("auto-expand", AutoExpandController);

import CharCounterController from "./char_counter_controller.js";
application.register("char-counter", CharCounterController);

import CheckboxLimitController from "./checkbox_limit_controller.js";
application.register("checkbox-limit", CheckboxLimitController);

import InvertedToggleController from "./inverted_toggle_controller.js";
application.register("inverted-toggle", InvertedToggleController);

import LiveValidationController from "./live_validation_controller.js";
application.register("live-validation", LiveValidationController);

import SaveBarController from "./save_bar_controller.js";
application.register("save-bar", SaveBarController);

import PartnershipSelectorController from "./partnership_selector_controller.js";
application.register("partnership-selector", PartnershipSelectorController);

import PartnerWizardController from "./partner_wizard_controller.js";
application.register("partner-wizard", PartnerWizardController);
