# frozen_string_literal: true

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require "cucumber/rails"
require "capybara/cucumber"
require "selenium-webdriver"

# Normal Island geocoder lookup is loaded via config/initializers/geocoder.rb
# UK postcode extension is loaded via lib/normal_island.rb

# FactoryBot is already loaded by cucumber-rails
# Just configure paths if not already set
FactoryBot.definition_file_paths = [Rails.root.join("spec/factories")] if FactoryBot.definition_file_paths.empty?

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail.
ActionController::Base.allow_rescue = false

# Database Cleaner configuration
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Cucumber::Rails::Database.javascript_strategy = :truncation

# Disable CSS animations for faster, more reliable tests
Capybara.disable_animation = true

# Selenium driver configuration - consistent with RSpec system tests
Capybara.register_driver :selenium_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument("--headless=new") unless ENV["HEADLESS"] == "false"
  options.add_argument("--window-size=1400,1400")
  options.add_argument("--disable-gpu")
  options.add_argument("--no-sandbox")
  options.add_argument("--disable-dev-shm-usage")

  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.javascript_driver = :selenium_headless

Capybara.configure do |config|
  config.default_max_wait_time = 5
  config.server = :puma, { Silent: true }
  config.always_include_port = true
end

# Use lvh.me for subdomain testing (resolves to 127.0.0.1)
# app_host: URL the browser uses to access the app (supports subdomains)
# server_host: Where Puma binds - must be 127.0.0.1 for CI compatibility
Capybara.app_host = "http://lvh.me"
Capybara.server_host = "127.0.0.1"

# Include FactoryBot methods in World
World(FactoryBot::Syntax::Methods)

# Freeze time for consistent test behavior
Before do
  Timecop.freeze(Time.zone.local(2022, 11, 8))
end

After do
  Timecop.return
end

# Use deletion for JavaScript scenarios (faster than truncation for PostgreSQL)
Before("@javascript") do
  DatabaseCleaner.strategy = :deletion
end

Before("not @javascript") do
  DatabaseCleaner.strategy = :transaction
end
