# frozen_string_literal: true

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require "cucumber/rails"
require "capybara/cucumber"
require "capybara/cuprite"

# Load shared spec support files (UK postcode stub, geocoder stubs)
require Rails.root.join("spec/support/uk_postcode_stub")
require Rails.root.join("spec/support/normal_island_geocoder")

# FactoryBot is already loaded by cucumber-rails
# Just configure paths if not already set
FactoryBot.definition_file_paths = [Rails.root.join("spec/factories")] if FactoryBot.definition_file_paths.empty?

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail.
ActionController::Base.allow_rescue = false

# Database Cleaner configuration
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Cucumber::Rails::Database.javascript_strategy = :truncation

# Disable CSS animations for faster, more reliable tests
Capybara.disable_animation = true

# Cuprite driver configuration - pure Ruby driver using Chrome DevTools Protocol
Capybara.register_driver :cuprite do |app|
  browser_opts = {}

  # CI/Docker environments need additional Chrome flags
  if ENV["DOCKER"] || ENV["CI"]
    browser_opts = {
      "no-sandbox" => nil,
      "disable-gpu" => nil,
      "disable-dev-shm-usage" => nil,
      "disable-software-rasterizer" => nil
    }
  end

  options = {
    window_size: [1400, 1400],
    js_errors: true,
    headless: ENV.fetch("HEADLESS", "true") != "false",
    slowmo: ENV["SLOWMO"]&.to_f,
    process_timeout: 30,
    timeout: 15,
    browser_options: browser_opts
  }
  # Use explicit Chrome path if provided (e.g., from GitHub Actions)
  options[:browser_path] = ENV["BROWSER_PATH"] if ENV["BROWSER_PATH"].present?

  Capybara::Cuprite::Driver.new(app, **options)
end

Capybara.javascript_driver = :cuprite

Capybara.configure do |config|
  config.default_max_wait_time = 5
  config.server = :puma, { Silent: true }
  config.always_include_port = true
end

# Use lvh.me for subdomain testing (resolves to 127.0.0.1)
Capybara.app_host = "http://lvh.me"
Capybara.server_host = "lvh.me"

# Include FactoryBot methods in World
World(FactoryBot::Syntax::Methods)

# Freeze time for consistent test behavior
Before do
  Timecop.freeze(Time.zone.local(2022, 11, 8))
end

After do
  Timecop.return
end

# Use deletion for JavaScript scenarios (faster than truncation for PostgreSQL)
Before("@javascript") do
  DatabaseCleaner.strategy = :deletion
end

Before("not @javascript") do
  DatabaseCleaner.strategy = :transaction
end
