# Database Consistency Configuration
# https://github.com/djezzzl/database_consistency

# Exclude models that don't have corresponding tables (HABTM join tables)
CollectionEvent:
  enabled: false # This is a HABTM join table (collections_events), not a standalone model

# OrganisationRelationship table exists but has no model - may be legacy/unused
OrganisationRelationship:
  enabled: false

# User model - Devise manages these token uniqueness constraints
User:
  index_users_on_invitation_token:
    enabled: false # Managed by Devise Invitable
  index_users_on_reset_password_token:
    enabled: false # Managed by Devise Recoverable
  # The sites association uses site_admin foreign key which is correct for has_many
  sites:
    enabled: false # site_admin column is indexed on sites table, foreign key is correct

# Site model - sites_neighbourhood is the join table, not a direct association
Site:
  sites_neighbourhood:
    enabled: false # This is a join table, indexed properly

# Neighbourhood model - addresses can exist without a neighbourhood
Neighbourhood:
  addresses:
    enabled: false # Intentional: addresses should persist if neighbourhood is deleted
