# frozen_string_literal: true
#
# RuboCop configuration for PlaceCal
# Organized by: Plugins, AllCops, then alphabetically by namespace
#

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-graphql
  - rubocop-rails

# =============================================================================
# AllCops - Global settings
# =============================================================================

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/schema.rb"

# =============================================================================
# GraphQL cops
# =============================================================================

GraphQL/FieldName:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

# =============================================================================
# Layout cops
# =============================================================================

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineContinuationSpacing:
  Enabled: false

# =============================================================================
# Lint cops
# =============================================================================

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/db.rake"

Lint/EmptyBlock:
  Exclude:
    - "lib/tasks/cucumber.rake"

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/RedundantStringCoercion:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

# =============================================================================
# Metrics cops
# =============================================================================

Metrics/ClassLength:
  Exclude:
    - "spec/**/*.rb"
    - "app/models/partner.rb"
    - "app/controllers/admin/partners_controller.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/controllers/application_controller.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/normal_island.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "app/controllers/application_controller.rb"

# =============================================================================
# Naming cops
# =============================================================================

Naming/BlockForwarding:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# =============================================================================
# Performance cops
# =============================================================================

Performance/MapMethodChain:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

# =============================================================================
# Rails cops
# =============================================================================

Rails/ActionOrder:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_day
    - find_by_request
    - find_by_sql
    - find_by_week

Rails/EnvLocal:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

# =============================================================================
# Rake cops
# =============================================================================

Rake/Desc:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rake/DuplicateTask:
  Exclude:
    - "lib/tasks/cucumber.rake"

# =============================================================================
# RSpec cops - Test suite configuration
# =============================================================================

# Allow multiple expectations in integration/request specs
RSpec/MultipleExpectations:
  Enabled: false

# Integration tests are naturally longer than unit tests
RSpec/ExampleLength:
  Enabled: false

# Allow deeper nesting for complex test scenarios
RSpec/NestedGroups:
  Max: 4

# Request and feature specs don't describe a specific class
RSpec/DescribeClass:
  Enabled: false

# Request specs describe endpoints not methods
RSpec/DescribeMethod:
  Enabled: false

# shared_examples_for is valid alongside shared_examples
RSpec/IncludeExamples:
  Enabled: false

# let! is valid for database setup that needs to run before tests
RSpec/LetSetup:
  Enabled: false

# Integration tests need more helpers than unit tests (default is 5)
RSpec/MultipleMemoizedHelpers:
  Max: 15

# Stubbing any instance is valid for testing external dependencies
RSpec/AnyInstance:
  Enabled: false

# Stylistic preference - "for X" reads better than "when X" in some cases
RSpec/ContextWording:
  Enabled: false

# Numbered variables (partner1, partner2) are readable in test contexts
RSpec/IndexedLet:
  Enabled: false

# Test-scoped constants are valid for test fixtures
RSpec/LeakyConstantDeclaration:
  Enabled: false

# instance_double requires exact class matching which isn't always feasible
RSpec/VerifiedDoubles:
  Enabled: false

# Request specs use descriptive paths like graphql/events_spec.rb
RSpec/SpecFilePathFormat:
  Enabled: false

# Helper methods with expectations are valid (check_source_has_events pattern)
RSpec/NoExpectationExample:
  Enabled: false

# Some spec files test related functionality across multiple top-level describes
RSpec/MultipleDescribes:
  Enabled: false

# Similar tests with different inputs are sometimes clearer than shared examples
RSpec/RepeatedExample:
  Enabled: false

# =============================================================================
# Style cops
# =============================================================================

Style/ArrayIntersect:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "lib/tasks/cucumber.rake"
    - "features/support/env.rb"
    - "spec/spec_helper.rb"

Style/HashEachMethods:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantCurrentDirectoryInPath:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RedundantLineContinuation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/SuperWithArgsParentheses:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
