inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-graphql
  - rubocop-rails
  
AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/schema.rb"
  SuggestExtensions: false

GraphQL/FieldName:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_day
    - find_by_request
    - find_by_sql
    - find_by_week

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/EnvLocal:
  Enabled: false

# all these added when updating ruby (and rubocop) - i guess a default config
# got updated. adding these here so we have the smallest code change in
# this branch

# RSpec configuration
# Request/system specs often need multiple expectations per example
RSpec/MultipleExpectations:
  Enabled: false

# Integration tests are naturally longer than unit tests
RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# Request and feature specs don't describe a specific class
RSpec/DescribeClass:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "spec/**/*.rb"
    - "test_legacy/**/*.rb"
    - "app/models/partner.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/normal_island.rb"

# Cucumber-generated files - exclude from style checks
Style/FrozenStringLiteralComment:
  Exclude:
    - "lib/tasks/cucumber.rake"
    - "features/support/env.rb"
    - "spec/spec_helper.rb"

Rake/Desc:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rake/DuplicateTask:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rails/RakeEnvironment:
  Exclude:
    - "lib/tasks/cucumber.rake"

Lint/EmptyBlock:
  Exclude:
    - "lib/tasks/cucumber.rake"

# shared_examples_for is valid - cop only accepts shared_examples
RSpec/IncludeExamples:
  Enabled: false

# let! is valid for database setup that needs to run before tests
RSpec/LetSetup:
  Enabled: false

# Integration tests need more helpers than unit tests (default is 5)
RSpec/MultipleMemoizedHelpers:
  Max: 15

# Stubbing any instance is valid for testing external dependencies
RSpec/AnyInstance:
  Enabled: false

# Stylistic preference - "for X" reads better than "when X" in some cases
RSpec/ContextWording:
  Enabled: false

# Numbered variables (partner1, partner2) are readable in test contexts
RSpec/IndexedLet:
  Enabled: false

# Test-scoped constants are valid for test fixtures
RSpec/LeakyConstantDeclaration:
  Enabled: false

# instance_double requires exact class matching which isn't always feasible
RSpec/VerifiedDoubles:
  Enabled: false

# Request specs use descriptive paths like graphql/events_spec.rb
RSpec/SpecFilePathFormat:
  Enabled: false

# Request specs describe endpoints not methods
RSpec/DescribeMethod:
  Enabled: false

# Helper methods with expectations are valid (check_source_has_events pattern)
RSpec/NoExpectationExample:
  Enabled: false

# Some spec files test related functionality across multiple top-level describes
RSpec/MultipleDescribes:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/db.rake"

# Similar tests with different inputs are sometimes clearer than shared examples
RSpec/RepeatedExample:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Rails/RootPathnameMethods:
  Enabled: false
GraphQL/MaxComplexitySchema:
  Enabled: false
GraphQL/MaxDepthSchema:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Rails/RedundantActiveRecordAllMethod:
  Enabled: false
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Performance/MapMethodChain:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/ArrayIntersect:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
Rails/FindEach:
  Enabled: false
Lint/RedundantStringCoercion:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Rails/Pluck:
  Enabled: false
Style/RedundantCurrentDirectoryInPath:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/SuperWithArgsParentheses:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/RedundantLineContinuation:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
