inherit_from: .rubocop_todo.yml

require:
  - rubocop-graphql
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/schema.rb"
  SuggestExtensions: false

GraphQL/FieldName:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_day
    - find_by_request
    - find_by_sql
    - find_by_week

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/EnvLocal:
  Enabled: false

# all these added when updating ruby (and rubocop) - i guess a default config
# got updated. adding these here so we have the smallest code change in
# this branch

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/AssertMatch:
  Enabled: false

Minitest/AssertOperator:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"
    - "app/models/partner.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Rails/RootPathnameMethods:
  Enabled: false
GraphQL/MaxComplexitySchema:
  Enabled: false
GraphQL/MaxDepthSchema:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Rails/RedundantActiveRecordAllMethod:
  Enabled: false
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Performance/MapMethodChain:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/ArrayIntersect:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
Rails/FindEach:
  Enabled: false
Lint/RedundantStringCoercion:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Rails/Pluck:
  Enabled: false
Style/RedundantCurrentDirectoryInPath:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/SuperWithArgsParentheses:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/RedundantLineContinuation:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
