inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-graphql
  - rubocop-rails
  
AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/schema.rb"
  SuggestExtensions: false

GraphQL/FieldName:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_day
    - find_by_request
    - find_by_sql
    - find_by_week

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/EnvLocal:
  Enabled: false

# all these added when updating ruby (and rubocop) - i guess a default config
# got updated. adding these here so we have the smallest code change in
# this branch

# RSpec configuration
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "spec/**/*.rb"
    - "test_legacy/**/*.rb"
    - "app/models/partner.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/normal_island.rb"

# Cucumber-generated files - exclude from style checks
Style/FrozenStringLiteralComment:
  Exclude:
    - "lib/tasks/cucumber.rake"
    - "features/support/env.rb"
    - "spec/spec_helper.rb"

Rake/Desc:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rake/DuplicateTask:
  Exclude:
    - "lib/tasks/cucumber.rake"

Rails/RakeEnvironment:
  Exclude:
    - "lib/tasks/cucumber.rake"

Lint/EmptyBlock:
  Exclude:
    - "lib/tasks/cucumber.rake"

RSpec/IncludeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/db.rake"

RSpec/RepeatedExample:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/application_controller.rb

Rails/RootPathnameMethods:
  Enabled: false
GraphQL/MaxComplexitySchema:
  Enabled: false
GraphQL/MaxDepthSchema:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Rails/RedundantActiveRecordAllMethod:
  Enabled: false
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Performance/MapMethodChain:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/ArrayIntersect:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
Rails/FindEach:
  Enabled: false
Lint/RedundantStringCoercion:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Rails/Pluck:
  Enabled: false
Style/RedundantCurrentDirectoryInPath:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/SuperWithArgsParentheses:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/RedundantLineContinuation:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
