language: ruby
dist: trusty
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database placecal_test;' -U postgres
before_install:
  - |
      if [ "$TRAVIS_BRANCH" = "production" ]; then
        openssl aes-256-cbc -K $encrypted_f4f309cbfdaf_key -iv $encrypted_f4f309cbfdaf_iv -in production-deploy.key.enc -out production-deploy.key -d
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        openssl aes-256-cbc -K $encrypted_87ceb08cf37e_key -iv $encrypted_87ceb08cf37e_iv -in deploy.key.enc -out deploy.key -d
      fi

deploy:
  - provider: script
    script: bash scripts/staging.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/production.sh
    on:
      branch: production

