# https://docs.appsignal.com/application/markers/deploy-markers.html

production:
  revision: <%= ENV['GIT_REV'] %>
  ignore_errors:
    - ActionController::BadRequest
staging:
  revision: <%= ENV['GIT_REV'] %>
  ignore_errors:
    - ActionController::BadRequest
