import { Behaviors } from './behaviors.base.js'
import './behaviors.calendar.js'
import './behaviors.collection.js'
import './behaviors.neighbourhood.js'
import './behaviors.partner.js'
import './behaviors.place.js'
import './behaviors.site.js'
import './behaviors.user.js'
