name: Deploy to staging

on:
  workflow_run:
    branches:
      - main
    workflows:
      - Test
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: dokku/github-action@v1.3.0
        with:
          git_remote_url: "ssh://dokku@placecal-staging.org:666/placecal"
          ssh_private_key: ${{ secrets.CI_STAGING_KEY }}
          branch: main
          ci_branch_name: main
