on:
  workflow_run:
    branches:
      - main
    workflows:
      - test
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: dokku/github-action@v1.3.0
        with:
          git_remote_url: "ssh://dokku@placecal-staging.org:666/placecal"
          ssh_private_key: ${{ secrets.CI_STAGING_KEY }}
          branch: main
          ci_branch_name: main
