name: Build, Test and Optionally Deploy

on: [push, pull_request, workflow_dispatch]

# According to: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
# Both Node and Yarn should be installed already
# This would ideally be split up into dependent jobs maybe, but this is a direct conversion of the travis script for now

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test
    services:
      postgres:
        image: postgres:13.4 # Same version as on the server
        env:
          POSTGRES_DB: placecal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: foobar
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Health options to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
# bundler cache is broken and does not correctly set up the rails binary :(
#        with: # ruby version specified in .ruby-version
#          bundler-cache: true # Automagically runs bundle install
      - name: Install bundler dependencies
        run: |
          bundle install
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 10.17.0
      - name: Do Tests
        run: |
          bundle exec rails webpacker:compile
          bundle exec rake
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          PGPASSWORD: foobar
      # Why was this run as the after-success step in travis?
      # - name: Precompile Assets
      #   run: |
      #     bundle exec rails assets:precompile
      - name: Deploy To Staging
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@placecal-staging.org:22/placecal-staging'
          ssh_private_key: ${{ secrets.CI_STAGING_KEY }}
          branch: main
          ci_branch_name: main
          git_push_flags: --force
      - name: Deploy To Production
        if: ${{ github.ref == 'refs/heads/production' }}
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@placecal.com:22/placecal'
          ssh_private_key: ${{ secrets.CI_PRODUCTION_KEY }}
          branch: main
          ci_branch_name: production
          git_push_flags: --force
