name: Build, Test and Optionally Deploy

on: [push, pull_request, workflow_dispatch]

# According to: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
# Both Node and Yarn should be installed already
# This would ideally be split up into dependent jobs maybe, but this is a direct conversion of the travis script for now

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test
    services:
      postgres:
        image: postgres:13.4 # Same version as on the server
        env:
          POSTGRES_DB: placecal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: foobar
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Health options to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Likely Solves the push issue, but will make everything slower
          fetch-depth: 0
      - name: Unshallow the repo provided to us
        run: |
          git fetch --unshallow origin
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
#        with: # ruby version specified in .ruby-version
#          bundler-cache: true # Automagically runs bundle install
      - name: Install bundler dependencies
        run: |
          bundle install
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 10.17.0
      - name: Do Tests
        run: |
          bundle exec rails webpacker:compile
          bundle exec rake
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          PGPASSWORD: foobar
      - name: Deploy To Staging
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_STAGING_KEY }}
          DOKKU_HOST: placecal-staging.org
          TARGET_REPO: placecal-staging
          TARGET_BRANCH: main
          SOURCE_BRANCH: main
      - name: Deploy To Production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_PRODUCTION_KEY }}
          DOKKU_HOST: placecal.com
          TARGET_REPO: placecal
          TARGET_BRANCH: production
          SOURCE_BRANCH: main
      - name: Precompile Assets
        run: |
          bundle exec rails assets:precompile
