on:
  - push
  - workflow_dispatch

# According to: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
# Both Node and Yarn should be installed already
# This would ideally be split up into dependent jobs maybe, but this is a direct conversion of the travis script for now

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4 # Same version as on the server
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: placecal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: foobar
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      PGPASSWORD: foobar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with: # ruby version specified in .ruby-version
          bundler-cache: true # Automagically runs bundle install
          cache-version: 3 # Invalidate originally used corrupted cache

      - uses: nodenv/actions/setup-nodenv@v2
      - uses: nodenv/actions/node-version@v2
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}
          cache: yarn
      - name: Install JS dependencies
        run: yarn install --immutable

      - name: Run unit tests
        run: bin/test --unit --no-fix
      - name: Run system tests
        run: bin/test --system --no-lint
      - name: Upload test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-screenshots
          path: tmp/screenshots/
          if-no-files-found: ignore
