on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4 # Same version as on the server
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: placecal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: foobar
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      PGPASSWORD: foobar

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 3

      - uses: nodenv/actions/setup-nodenv@v2
      - uses: nodenv/actions/node-version@v2
        id: nodenv
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}
          cache: yarn
      - run: yarn install --immutable

      - run: bin/test --unit --no-fix
      - run: bin/test --system --no-lint
      - if: failure()
        name: Upload test screenshots
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: tmp/screenshots/
          if-no-files-found: ignore
